Repository shivammathur/setup-php, pull requests merged in 2019-12, with the labels that each got.

#101 1.5.7
  __tests__/extensions.test.ts
  action.yml
  dist/index.js
  package-lock.json
  package.json
  src/extensions.ts
  src/scripts/darwin.sh
Labels: release

#103 1.5.8
  README.md
  package-lock.json
  package.json
  src/scripts/win32.ps1
Labels: release

#106 Fix coverage log for Xdebug on PHP 8.0
  .github/workflows/experimental-workflow.yml
  __tests__/coverage.test.ts
  dist/index.js
  src/coverage.ts
Labels: Hotfix

#119 1.6.1
  README.md
  __tests__/extensions.test.ts
  __tests__/install.test.ts
  dist/index.js
  package-lock.json
  package.json
  src/extensions.ts
  src/install.ts
  src/scripts/gearman.sh
  src/scripts/linux.sh
Labels: release

#121 Fix add_extension on linux and macOS
  src/scripts/darwin.sh
  src/scripts/linux.sh
Labels: Hotfix

#84 Add problem matcher for PHPUnit
  .github/matchers/phpunit.json
  __tests__/install.test.ts
  src/install.ts
  src/matchers.ts
Labels: enhancement

#124 1.6.2
  .github/workflows/experimental-workflow.yml
  .github/workflows/workflow.yml
  README.md
  __tests__/matchers.test.ts
  action.yml
  dist/index.js
  package-lock.json
  package.json
  src/configs/phpunit.json
  src/ext/php_pcov.dll
  src/install.ts
  src/matchers.ts
  src/scripts/darwin.sh
  src/scripts/linux.sh
  src/scripts/win32.ps1
Labels: release

#125 Remove coverage drivers completely if requested
  __tests__/coverage.test.ts
  dist/index.js
  package-lock.json
  src/coverage.ts
Labels: enhancement

#127 Hotfix to support phalcon after v4 release
  __tests__/extensions.test.ts
  dist/index.js
  src/extensions.ts
  src/scripts/phalcon.sh
Labels: Hotfix

#133 1.7.0
  README.md
  __tests__/coverage.test.ts
  __tests__/extensions.test.ts
  __tests__/install.test.ts
  __tests__/tools.test.ts
  __tests__/utils.test.ts
  action.yml
  dist/index.js
  examples/bedrock.yml
  examples/codeigniter.yml
  examples/laravel-mysql.yml
  examples/laravel-postgres.yml
  examples/laravel.yml
  examples/lumen-mysql.yml
  examples/lumen-postgres.yml
  examples/lumen.yml
  examples/phalcon-mysql.yml
  examples/phalcon-postgres.yml
  examples/sage.yml
  examples/slim-framework.yml
  examples/symfony-mysql.yml
  examples/symfony-postgres.yml
  examples/symfony.yml
  examples/yii2-mysql.yml
  examples/yii2-postgres.yml
  examples/zend-framework.yml
  package-lock.json
  package.json
  src/bin/php_pcov.dll
  src/config.ts
  src/coverage.ts
  src/extensions.ts
  src/install.ts
  src/scripts/7.4.sh
  src/scripts/darwin.sh
  src/scripts/ext/gearman.sh
  src/scripts/ext/pcov.sh
  src/scripts/ext/phalcon.ps1
  src/scripts/ext/phalcon.sh
  src/scripts/ext/phalcon_darwin.sh
  src/scripts/ext/xdebug.sh
  src/scripts/ext/xdebug_darwin.sh
  src/scripts/linux.sh
  src/scripts/win32.ps1
  src/tools.ts
  src/utils.ts
Labels: release
